#!/usr/bin/env bash

err() {
    local msg="${1}"
    echo "${msg}" >&2 && exit 1
}

main() {
    local proj="${1}"

    git remote add "${proj}" "git@github.com:daved/${proj}.git" || err "cannot add remote"
    git fetch "${proj}" || err "cannot fetch remote"
    git merge --no-edit --allow-unrelated-histories "${proj}"/master || err "cannot merge remote"

    local files=$(git ls-tree -tr ${proj}/master --name-only)
    [[ $? -eq 0 ]] || err "cannot get files from remote"

    mkdir ${proj} || err "cannot mkdir '${proj}'"

    while read -r file; do
        mv "${file}" "./${proj}" || err "cannot move file '${file}'"   
    done <<< "${files}"

    git add . || err "cannot add all"
    git commit -m"Move ${proj} into subdir." || err "cannot commit move into subdir"

    local storeDir="../SUB"

    mkdir -p "${storeDir}" || err "cannot mkdir '${storeDir}'"
    mv "../${proj}" "${storeDir}" || err "cannot move '../${proj}' to '${storeDir}'"

    git remote remove "${proj}" || err "cannot remove remote"
}

main "${1}"
