package zones

import (
	"errors"
	"strings"
	"time"
)

var (
	ErrZoneNotFound = errors.New("zone not found")

	zoneMap = map[string]string{
		"ACST":  "Australia/Adelaide",
		"AEST":  "Australia/Brisbane",
		"AFT":   "Asia/Kabul",
		"AKST":  "America/Anchorage",
		"AKDT":  "America/Anchorage",
		"ALMT":  "Asia/Almaty",
		"AMT":   "America/Campo_Grande",
		"AMST":  "America/Campo_Grande",
		"ANAT":  "Asia/Anadyr",
		"ANAST": "Asia/Anadyr",
		"AQTT":  "Asia/Aqtau",
		"ART":   "America/Argentina/Buenos_Aires",
		"AST":   "Atlantic/Bermuda",
		"ADT":   "Atlantic/Bermuda",
		"AWST":  "Australia/Perth",
		"AZOT":  "Atlantic/Azores",
		"AZOST": "Atlantic/Azores",
		"AZT":   "Asia/Baku",
		"AZST":  "Asia/Baku",
		"BDST":  "Asia/Dhaka",
		"BNT":   "Asia/Brunei",
		"BOT":   "America/La_Paz",
		"BRT":   "America/Sao_Paulo",
		"BRST":  "America/Sao_Paulo",
		"BTT":   "Asia/Thimphu",
		"BVIS":  "Antarctica/Bouvet",
		"CAT":   "Africa/Bujumbura",
		"CCT":   "Indian/Cocos",
		"CET":   "Europe/Andorra",
		"CEST":  "Europe/Andorra",
		"CHAST": "Pacific/Chatham",
		"CHAD":  "Pacific/Chatham",
		"CHOT":  "Asia/Choibalsan",
		"CHOST": "Asia/Choibalsan",
		"ChST":  "Pacific/Chuuk",
		"CHUT":  "Pacific/Chuuk",
		"CIT":   "Asia/Makassar",
		"CLT":   "America/Santiago",
		"CLST":  "America/Santiago",
		"COT":   "America/Bogota",
		"CST":   "America/Rainy_River",
		"CDT":   "America/Rainy_River",
		"CT":    "Asia/Macau",
		"CVT":   "Atlantic/Cape_Verde",
		"CWST":  "Australia/Eucla",
		"EAST":  "Pacific/Easter",
		"EASST": "Pacific/Easter",
		"EAT":   "Africa/Djibouti",
		"ECT":   "America/Guayaquil",
		"EET":   "Europe/Mariehamn",
		"EEST":  "Europe/Mariehamn",
		"EGT":   "America/Scoresbysund",
		"EGST":  "America/Scoresbysund",
		"EIT":   "Asia/Jayapura",
		"EST":   "America/Nassau",
		"EDT":   "America/Nassau",
		"FJT":   "Pacific/Fiji",
		"FKT":   "Atlantic/Stanley",
		"FKST":  "Atlantic/Stanley",
		"FNT":   "America/Noronha",
		"GALT":  "Pacific/Galapagos",
		"GAMT":  "Pacific/Gambier",
		"GET":   "Asia/Tbilisi",
		"GFT":   "America/Cayenne",
		"GILT":  "Pacific/Tarawa",
		"GMT":   "Europe/London",
		"BST":   "Europe/London",
		"GST":   "Asia/Dubai",
		"GYT":   "America/Guyana",
		"HAST":  "America/Adak",
		"HADT":  "America/Adak",
		"HIMI":  "Australia/Heard_and_McDonald",
		"HKT":   "Asia/Hong_Kong",
		"HOVT":  "Asia/Hovd",
		"HOVST": "Asia/Hovd",
		"ICT":   "Asia/Phnom_Penh",
		"IRKT":  "Asia/Irkutsk",
		"IRKST": "Asia/Irkutsk",
		"IRST":  "Asia/Tehran",
		"IST":   "Asia/Jerusalem",
		"IDT":   "Asia/Jerusalem",
		"JST":   "Asia/Tokyo",
		"KGT":   "Asia/Bishkek",
		"KOST":  "Pacific/Kosrae",
		"KRAT":  "Asia/Krasnoyarsk",
		"KRAST": "Asia/Krasnoyarsk",
		"KST":   "Asia/Pyongyang",
		"LHST":  "Australia/Lord_Howe",
		"LINT":  "Indian/Christmas",
		"LKT":   "Asia/Colombo",
		"MAGT":  "Asia/Magadan",
		"MAGST": "Asia/Magadan",
		"MART":  "Pacific/Marquesas",
		"MHT":   "Pacific/Kwajalein",
		"MMT":   "Asia/Rangoon",
		"MSK":   "Europe/Moscow",
		"MSD":   "Europe/Moscow",
		"MST":   "America/Cambridge_Bay",
		"MDT":   "America/Cambridge_Bay",
		"MUT":   "Indian/Mauritius",
		"MVT":   "Indian/Maldives",
		"MYT":   "Asia/Kuala_Lumpur",
		"NCT":   "Pacific/Noumea",
		"NFT":   "Pacific/Norfolk",
		"NOVT":  "Asia/Novokuznetsk",
		"NOVST": "Asia/Novokuznetsk",
		"NPT":   "Asia/Kathmandu",
		"NRT":   "Pacific/Nauru",
		"NST":   "America/St_Johns",
		"NDT":   "America/St_Johns",
		"NUT":   "Pacific/Niue",
		"NZST":  "Pacific/Auckland",
		"NZDT":  "Pacific/Auckland",
		"OMST":  "Asia/Omsk",
		"OMSST": "Asia/Omsk",
		"ORAT":  "Asia/Oral",
		"PET":   "America/Lima",
		"PETT":  "Asia/Kamchatka",
		"PETST": "Asia/Kamchatka",
		"PGT":   "Pacific/Port_Moresby",
		"PHOT":  "Pacific/Enderbury",
		"PHT":   "Asia/Manila",
		"PKT":   "Asia/Karachi",
		"PKST":  "Asia/Karachi",
		"PMST":  "America/Miquelon",
		"PMDT":  "America/Miquelon",
		"PST":   "America/Dawson",
		"PDT":   "America/Dawson",
		"PWT":   "Pacific/Palau",
		"PYT":   "America/Asuncion",
		"PYST":  "America/Asuncion",
		"QYZT":  "Asia/Qyzylorda",
		"RET":   "Indian/Reunion",
		"SAKT":  "Asia/Sakhalin",
		"SAKST": "Asia/Sakhalin",
		"SAMT":  "Europe/Samara",
		"SAMST": "Europe/Samara",
		"SAST":  "Africa/Maseru",
		"SBT":   "Pacific/Guadalcanal",
		"SCT":   "Indian/Mahe",
		"SGT":   "Asia/Singapore",
		"SRT":   "America/Paramaribo",
		"SST":   "Pacific/Pago_Pago",
		"TAHT":  "Pacific/Tahiti",
		"TFT":   "Indian/Kerguelen",
		"TJT":   "Asia/Dushanbe",
		"TKT":   "Pacific/Fakaofo",
		"TLT":   "Asia/Dili",
		"TMT":   "Asia/Ashgabat",
		"TOT":   "Pacific/Tongatapu",
		"TVT":   "Pacific/Funafuti",
		"ULAT":  "Asia/Ulaanbaatar",
		"ULAST": "Asia/Ulaanbaatar",
		"UYT":   "America/Montevideo",
		"UYST":  "America/Montevideo",
		"UZT":   "Asia/Samarkand",
		"VET":   "America/Caracas",
		"VLAT":  "Asia/Vladivostok",
		"VLAST": "Asia/Vladivostok",
		"VOLT":  "Europe/Volgograd",
		"VOLST": "Europe/Volgograd",
		"VUT":   "Pacific/Efate",
		"WAT":   "Africa/Windhoek",
		"WAST":  "Africa/Windhoek",
		"WET":   "Atlantic/Canary",
		"WEST":  "Atlantic/Canary",
		"WFT":   "Pacific/Wallis",
		"WGT":   "America/Godthab",
		"WGST":  "America/Godthab",
		"WIB":   "Asia/Jakarta",
		"WST":   "Pacific/Apia",
		"YAKT":  "Asia/Yakutsk",
		"YAKST": "Asia/Yakutsk",
		"YEKT":  "Asia/Yekaterinburg",
		"YEKST": "Asia/Yekaterinburg",
	}
)

func LocByZone(zone string) (*time.Location, error) {
	locName, ok := zoneMap[strings.ToUpper(zone)]
	if !ok {
		return nil, ErrZoneNotFound
	}

	loc, err := time.LoadLocation(locName)
	if err != nil {
		return nil, ErrZoneNotFound
	}

	return loc, nil
}
